- name: Install Kubernetes components
  hosts: nodes
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: [ 'curl', 'apt-transport-https', 'ca-certificates', 'software-properties-common', 'conntrack' ]
        state: present

    - name: Install Docker (as runtime for Minikube)
      apt:
        name: docker.io
        state: present

    - name: Download Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Download kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ lookup('pipe', 'curl -L -s https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install Helm via script
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Start Minikube (using Docker driver)
      shell: minikube start --driver=docker --force
      become: no # Запускаємо від звичайного користувача, якщо треба, але тут для root