name: "Ansible Installation Task 2"

on:
  workflow_dispatch: # Запускаємо вручну після того, як сервер готовий

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ekzamen
          chmod 600 ekzamen

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Ansible Check (Validation)
        run: |
          ansible-playbook -i task2/inventory.ini task2/playbook.yml --check --extra-vars "ansible_ssh_private_key_file=ekzamen"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

      - name: Ansible Apply (Real Install)
        run: |
          ansible-playbook -i task2/inventory.ini task2/playbook.yml --extra-vars "ansible_ssh_private_key_file=ekzamen"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
